import type { Entrance } from "./entrance";
import type { LatLng } from "./construction";

export type RoutePreference = "fastest" | "accessible" | "avoidConstruction";

export type RouteWarningType =
  | "stairs"
  | "steep-incline"
  | "construction"
  | "elevator-dependent"
  | "narrow-path"
  | "entrance-closed"
  | "no-accessible-entrance";

export type RouteWarningSeverity = "info" | "caution" | "high";

export interface RouteWarning {
  type: RouteWarningType;
  label: string;
  severity: RouteWarningSeverity;
  description: string;
}

export interface RouteEndpoint {
  /** Display label — a place's official name, an entrance label, or "My Location". */
  label: string;
  coordinate: LatLng;
}

export interface RouteRequest {
  origin: RouteEndpoint;
  destination: RouteEndpoint;
  preference: RoutePreference;
  /**
   * Entrances belonging to the destination place, if any. Lets the mock
   * routing engine target a specific accessible entrance for the
   * "accessible" preference instead of the place's raw coordinate.
   */
  destinationEntrances?: Entrance[];
}

export interface RouteStep {
  id: string;
  instruction: string;
  distanceMeters: number;
}

export interface Route {
  id: string;
  coordinates: LatLng[];
  distanceMeters: number;
  durationMinutes: number;
  preference: RoutePreference;
  warnings: RouteWarning[];
  /** Simulated turn-by-turn-style steps — mocked from route geometry, not real GPS. */
  steps: RouteStep[];
  originLabel: string;
  destinationLabel: string;
  /** Set when the "accessible" preference routed to a specific accessible entrance. */
  accessibleEntranceLabel?: string;
  /**
   * Always true. This route is generated by the mock routing engine for
   * demo/prototyping purposes — not real GPS turn-by-turn navigation.
   * Kept on the data itself (not just in UI copy) so nothing consuming a
   * Route can accidentally present it as live navigation.
   */
  isSimulated: true;
}
